# Docker Compose for HPmini IoT Stack
services:
  # Second Mosquitto instance for your IoT System
  mosquitto_iot:
    image: eclipse-mosquitto
    ports:
      - "8884:1883" # Mapping internal 1883 to external 8884
      - "9001:9001" # Websockets (optional for web dashboards)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    networks:
      - iot_net
    restart: unless-stopped

  # Database for long-term storage
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - iot_net
    restart: unless-stopped
  
    #  for dataflow from mangoDB to grafana
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    depends_on:
      - mongodb
      - mosquitto_iot
    networks:
      - iot_net
    restart: unless-stopped

  # Dashboard
  grafana2:
    image: grafana/grafana
    ports:
      - "3003:3000"
    depends_on:
      - node-red
    environment:
      - GF_INSTALL_PLUGINS=grafana-mongodb-datasource 
    networks:
      - iot_net
    restart: unless-stopped


networks:
  iot_net:
    driver: bridge
