per_listener_settings true

# Слушатель для ESP32 (SSL/TLS)
listener 1883
# Пути внутри контейнера (как мы прописали в volumes)
require_certificate false
# use_identity_as_username true
allow_anonymous true
# Разрешаем вход без пароля (для теста)

# Хранение данных, если брокер перезагрузится
persistence true
persistence_location /mosquitto/data/

# Логирование (поможет увидеть, приходят ли данные от RasPi)
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
