# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x07sensors\"Y\n\rSensorReading\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x0e\n\x06sensor\x18\x02 \x01(\t\x12\r\n\x05units\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\x12\n\n\x02ts\x18\x05 \x01(\x03\"Y\n\rGatewayStatus\x12\x12\n\ngateway_id\x18\x01 \x01(\t\x12\x0b\n\x03\x63pu\x18\x02 \x01(\x01\x12\x0b\n\x03ram\x18\x03 \x01(\x01\x12\x0e\n\x06uptime\x18\x04 \x01(\x01\x12\n\n\x02ts\x18\x05 \x01(\x03\"Z\n\x05\x42\x61tch\x12(\n\x08readings\x18\x01 \x03(\x0b\x32\x16.sensors.SensorReading\x12\'\n\x07gateway\x18\x02 \x01(\x0b\x32\x16.sensors.GatewayStatusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORREADING._serialized_start=25
  _SENSORREADING._serialized_end=114
  _GATEWAYSTATUS._serialized_start=116
  _GATEWAYSTATUS._serialized_end=205
  _BATCH._serialized_start=207
  _BATCH._serialized_end=297
# @@protoc_insertion_point(module_scope)
